# Generated by Django 4.1 on 2022-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_extenduser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
    ]
