# Generated by Django 4.1 on 2022-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Acceptance'), ('3', 'Rejected')], default='1', max_length=15),
        ),
    ]
